### PR TITLE
feat: add navigation buttons on Home Page

### PR DESCRIPTION
**Pull request by tushar-2811**
#1 #2 

 1. Added Two Navigation buttons on the home page, which would eventually make navigation between sign In and Sign up pages smooth.
 2. Updated the signIn and signUp form with new links to improve the navigation between two pages.

Screenshot 2024-05-23 092255

Updated Sign Up page.
Screenshot 2024-05-23 120529

Updated Sign In page.
Screenshot 2024-05-23 120824

This is how the dashboard looks like when user is signed in.
Screenshot 2024-05-23 120634

### CODE REVIEW

**Comment by ShauryaSood2003** [comment]
Looks great, but a few changes are needed:

1. When userInfo is true, please style the "Go to Problem List" button. Ensure it matches the styling of the buttons in the Header component for consistency.
2. If userInfo is false (null), you've added the Header component, which is great. However, in this case, the Link tag for signup is not needed and should be removed.

**Comment by tushar-2811** [comment]
working on that, Sir!

**Comment by ShauryaSood2003** [comment]
Also make the pull req to the #2 issue as that issue deal with the home page ui enhancement here you just need to add a simple navigate("/signin") or navigate("/signup") to signin/up pages of user and admin where they route to required pages like in the image attached
Screenshot 2024-05-23 112003
[https://github.com/ShauryaSood2003/CodeCrack/tree/main/frontEnd/src/components](https://github.com/ShauryaSood2003/CodeCrack/issues/url) in this the signin signup folder

**Comment by ShauryaSood2003** [comment]
great work 👍

**Pull request merged**
